CREATE TABLE pasteis_salgados (
    id_pastel_salgado INT(11) NOT NULL AUTO_INCREMENT,
    recheios VARCHAR(255) NOT NULL,
    preco DECIMAL(4,2),
    PRIMARY KEY(id_pastel_salgado)
);

INSERT INTO pasteis_salgados (recheios) VALUES 
    ('Champignon, Calabresa, Catupiry'),
    ('Champignon, Calabresa, Tomate'),
    ('Champignon, Calabresa, Cheddar'),
    ('Champignon, Calabresa, Bacon'),
    ('Champignon, Calabresa, Lombo'),
    ('Champignon, Calabresa, Ovo'),
    ('Champignon, Calabresa, Presunto'),
    ('Champignon, Calabresa, Frango'),
    ('Champignon, Calabresa, Palmito'),
    ('Champignon, Calabresa, Azeitona'),
    ('Champignon, Calabresa, Milho'),
    ('Champignon, Calabresa, Carne Moida'),
    ('Champignon, Calabresa, Brócolis'),
    ('Champignon, Calabresa, Mussarela'),
    ('Champignon, Calabresa, Perpperoni'),
    ('Champignon, Calabresa, Carne Seca'),
    ('Champignon, Catupiry, Tomate'),
    ('Champignon, Catupiry, Cheddar'),
    ('Champignon, Catupiry, Bacon'),
    ('Champignon, Catupiry, Lombo'),
    ('Champignon, Catupiry, Ovo'),
    ('Champignon, Catupiry, Presunto'),
    ('Champignon, Catupiry, Frango'),
    ('Champignon, Catupiry, Palmito'),
    ('Champignon, Catupiry, Azeitona'),
    ('Champignon, Catupiry, Milho'),
    ('Champignon, Catupiry, Carne Moida'),
    ('Champignon, Catupiry, Brócolis'),
    ('Champignon, Catupiry, Mussarela'),
    ('Champignon, Catupiry, Perpperoni'),
    ('Champignon, Catupiry, Carne Seca'),
    ('Champignon, Tomate, Cheddar'),
    ('Champignon, Tomate, Bacon'),
    ('Champignon, Tomate, Lombo'),
    ('Champignon, Tomate, Ovo'),
    ('Champignon, Tomate, Presunto'),
    ('Champignon, Tomate, Frango'),
    ('Champignon, Tomate, Palmito'),
    ('Champignon, Tomate, Azeitona'),
    ('Champignon, Tomate, Milho'),
    ('Champignon, Tomate, Carne Moida'),
    ('Champignon, Tomate, Brócolis'),
    ('Champignon, Tomate, Mussarela'),
    ('Champignon, Tomate, Perpperoni'),
    ('Champignon, Tomate, Carne Seca'),
    ('Champignon, Cheddar, Bacon'),
    ('Champignon, Cheddar, Lombo'),
    ('Champignon, Cheddar, Ovo'),
    ('Champignon, Cheddar, Presunto'),
    ('Champignon, Cheddar, Frango'),
    ('Champignon, Cheddar, Palmito'),
    ('Champignon, Cheddar, Azeitona'),
    ('Champignon, Cheddar, Milho'),
    ('Champignon, Cheddar, Carne Moida'),
    ('Champignon, Cheddar, Brócolis'),
    ('Champignon, Cheddar, Mussarela'),
    ('Champignon, Cheddar, Perpperoni'),
    ('Champignon, Cheddar, Carne Seca'),
    ('Champignon, Bacon, Lombo'),
    ('Champignon, Bacon, Ovo'),
    ('Champignon, Bacon, Presunto'),
    ('Champignon, Bacon, Frango'),
    ('Champignon, Bacon, Palmito'),
    ('Champignon, Bacon, Azeitona'),
    ('Champignon, Bacon, Milho'),
    ('Champignon, Bacon, Carne Moida'),
    ('Champignon, Bacon, Brócolis'),
    ('Champignon, Bacon, Mussarela'),
    ('Champignon, Bacon, Perpperoni'),
    ('Champignon, Bacon, Carne Seca'),
    ('Champignon, Lombo, Ovo'),
    ('Champignon, Lombo, Presunto'),
    ('Champignon, Lombo, Frango'),
    ('Champignon, Lombo, Palmito'),
    ('Champignon, Lombo, Azeitona'),
    ('Champignon, Lombo, Milho'),
    ('Champignon, Lombo, Carne Moida'),
    ('Champignon, Lombo, Brócolis'),
    ('Champignon, Lombo, Mussarela'),
    ('Champignon, Lombo, Perpperoni'),
    ('Champignon, Lombo, Carne Seca'),
    ('Champignon, Ovo, Presunto'),
    ('Champignon, Ovo, Frango'),
    ('Champignon, Ovo, Palmito'),
    ('Champignon, Ovo, Azeitona'),
    ('Champignon, Ovo, Milho'),
    ('Champignon, Ovo, Carne Moida'),
    ('Champignon, Ovo, Brócolis'),
    ('Champignon, Ovo, Mussarela'),
    ('Champignon, Ovo, Perpperoni'),
    ('Champignon, Ovo, Carne Seca'),
    ('Champignon, Presunto, Frango'),
    ('Champignon, Presunto, Palmito'),
    ('Champignon, Presunto, Azeitona'),
    ('Champignon, Presunto, Milho'),
    ('Champignon, Presunto, Carne Moida'),
    ('Champignon, Presunto, Brócolis'),
    ('Champignon, Presunto, Mussarela'),
    ('Champignon, Presunto, Perpperoni'),
    ('Champignon, Presunto, Carne Seca'),
    ('Champignon, Frango, Palmito'),
    ('Champignon, Frango, Azeitona'),
    ('Champignon, Frango, Milho'),
    ('Champignon, Frango, Carne Moida'),
    ('Champignon, Frango, Brócolis'),
    ('Champignon, Frango, Mussarela'),
    ('Champignon, Frango, Perpperoni'),
    ('Champignon, Frango, Carne Seca'),
    ('Champignon, Palmito, Azeitona'),
    ('Champignon, Palmito, Milho'),
    ('Champignon, Palmito, Carne Moida'),
    ('Champignon, Palmito, Brócolis'),
    ('Champignon, Palmito, Mussarela'),
    ('Champignon, Palmito, Perpperoni'),
    ('Champignon, Palmito, Carne Seca'),
    ('Champignon, Azeitona, Milho'),
    ('Champignon, Azeitona, Carne Moida'),
    ('Champignon, Azeitona, Brócolis'),
    ('Champignon, Azeitona, Mussarela'),
    ('Champignon, Azeitona, Perpperoni'),
    ('Champignon, Azeitona, Carne Seca'),
    ('Champignon, Milho, Carne Moida'),
    ('Champignon, Milho, Brócolis'),
    ('Champignon, Milho, Mussarela'),
    ('Champignon, Milho, Perpperoni'),
    ('Champignon, Milho, Carne Seca'),
    ('Champignon, Carne Moida, Brócolis'),
    ('Champignon, Carne Moida, Mussarela'),
    ('Champignon, Carne Moida, Perpperoni'),
    ('Champignon, Carne Moida, Carne Seca'),
    ('Champignon, Brócolis, Mussarela'),
    ('Champignon, Brócolis, Perpperoni'),
    ('Champignon, Brócolis, Carne Seca'),
    ('Champignon, Mussarela, Perpperoni'),
    ('Champignon, Mussarela, Carne Seca'),
    ('Champignon, Perpperoni, Carne Seca'),
    ('Calabresa, Catupiry, Tomate'),
    ('Calabresa, Catupiry, Cheddar'),
    ('Calabresa, Catupiry, Bacon'),
    ('Calabresa, Catupiry, Lombo'),
    ('Calabresa, Catupiry, Ovo'),
    ('Calabresa, Catupiry, Presunto'),
    ('Calabresa, Catupiry, Frango'),
    ('Calabresa, Catupiry, Palmito'),
    ('Calabresa, Catupiry, Azeitona'),
    ('Calabresa, Catupiry, Milho'),
    ('Calabresa, Catupiry, Carne Moida'),
    ('Calabresa, Catupiry, Brócolis'),
    ('Calabresa, Catupiry, Mussarela'),
    ('Calabresa, Catupiry, Perpperoni'),
    ('Calabresa, Catupiry, Carne Seca'),
    ('Calabresa, Tomate, Cheddar'),
    ('Calabresa, Tomate, Bacon'),
    ('Calabresa, Tomate, Lombo'),
    ('Calabresa, Tomate, Ovo'),
    ('Calabresa, Tomate, Presunto'),
    ('Calabresa, Tomate, Frango'),
    ('Calabresa, Tomate, Palmito'),
    ('Calabresa, Tomate, Azeitona'),
    ('Calabresa, Tomate, Milho'),
    ('Calabresa, Tomate, Carne Moida'),
    ('Calabresa, Tomate, Brócolis'),
    ('Calabresa, Tomate, Mussarela'),
    ('Calabresa, Tomate, Perpperoni'),
    ('Calabresa, Tomate, Carne Seca'),
    ('Calabresa, Cheddar, Bacon'),
    ('Calabresa, Cheddar, Lombo'),
    ('Calabresa, Cheddar, Ovo'),
    ('Calabresa, Cheddar, Presunto'),
    ('Calabresa, Cheddar, Frango'),
    ('Calabresa, Cheddar, Palmito'),
    ('Calabresa, Cheddar, Azeitona'),
    ('Calabresa, Cheddar, Milho'),
    ('Calabresa, Cheddar, Carne Moida'),
    ('Calabresa, Cheddar, Brócolis'),
    ('Calabresa, Cheddar, Mussarela'),
    ('Calabresa, Cheddar, Perpperoni'),
    ('Calabresa, Cheddar, Carne Seca'),
    ('Calabresa, Bacon, Lombo'),
    ('Calabresa, Bacon, Ovo'),
    ('Calabresa, Bacon, Presunto'),
    ('Calabresa, Bacon, Frango'),
    ('Calabresa, Bacon, Palmito'),
    ('Calabresa, Bacon, Azeitona'),
    ('Calabresa, Bacon, Milho'),
    ('Calabresa, Bacon, Carne Moida'),
    ('Calabresa, Bacon, Brócolis'),
    ('Calabresa, Bacon, Mussarela'),
    ('Calabresa, Bacon, Perpperoni'),
    ('Calabresa, Bacon, Carne Seca'),
    ('Calabresa, Lombo, Ovo'),
    ('Calabresa, Lombo, Presunto'),
    ('Calabresa, Lombo, Frango'),
    ('Calabresa, Lombo, Palmito'),
    ('Calabresa, Lombo, Azeitona'),
    ('Calabresa, Lombo, Milho'),
    ('Calabresa, Lombo, Carne Moida'),
    ('Calabresa, Lombo, Brócolis'),
    ('Calabresa, Lombo, Mussarela'),
    ('Calabresa, Lombo, Perpperoni'),
    ('Calabresa, Lombo, Carne Seca'),
    ('Calabresa, Ovo, Presunto'),
    ('Calabresa, Ovo, Frango'),
    ('Calabresa, Ovo, Palmito'),
    ('Calabresa, Ovo, Azeitona'),
    ('Calabresa, Ovo, Milho'),
    ('Calabresa, Ovo, Carne Moida'),
    ('Calabresa, Ovo, Brócolis'),
    ('Calabresa, Ovo, Mussarela'),
    ('Calabresa, Ovo, Perpperoni'),
    ('Calabresa, Ovo, Carne Seca'),
    ('Calabresa, Presunto, Frango'),
    ('Calabresa, Presunto, Palmito'),
    ('Calabresa, Presunto, Azeitona'),
    ('Calabresa, Presunto, Milho'),
    ('Calabresa, Presunto, Carne Moida'),
    ('Calabresa, Presunto, Brócolis'),
    ('Calabresa, Presunto, Mussarela'),
    ('Calabresa, Presunto, Perpperoni'),
    ('Calabresa, Presunto, Carne Seca'),
    ('Calabresa, Frango, Palmito'),
    ('Calabresa, Frango, Azeitona'),
    ('Calabresa, Frango, Milho'),
    ('Calabresa, Frango, Carne Moida'),
    ('Calabresa, Frango, Brócolis'),
    ('Calabresa, Frango, Mussarela'),
    ('Calabresa, Frango, Perpperoni'),
    ('Calabresa, Frango, Carne Seca'),
    ('Calabresa, Palmito, Azeitona'),
    ('Calabresa, Palmito, Milho'),
    ('Calabresa, Palmito, Carne Moida'),
    ('Calabresa, Palmito, Brócolis'),
    ('Calabresa, Palmito, Mussarela'),
    ('Calabresa, Palmito, Perpperoni'),
    ('Calabresa, Palmito, Carne Seca'),
    ('Calabresa, Azeitona, Milho'),
    ('Calabresa, Azeitona, Carne Moida'),
    ('Calabresa, Azeitona, Brócolis'),
    ('Calabresa, Azeitona, Mussarela'),
    ('Calabresa, Azeitona, Perpperoni'),
    ('Calabresa, Azeitona, Carne Seca'),
    ('Calabresa, Milho, Carne Moida'),
    ('Calabresa, Milho, Brócolis'),
    ('Calabresa, Milho, Mussarela'),
    ('Calabresa, Milho, Perpperoni'),
    ('Calabresa, Milho, Carne Seca'),
    ('Calabresa, Carne Moida, Brócolis'),
    ('Calabresa, Carne Moida, Mussarela'),
    ('Calabresa, Carne Moida, Perpperoni'),
    ('Calabresa, Carne Moida, Carne Seca'),
    ('Calabresa, Brócolis, Mussarela'),
    ('Calabresa, Brócolis, Perpperoni'),
    ('Calabresa, Brócolis, Carne Seca'),
    ('Calabresa, Mussarela, Perpperoni'),
    ('Calabresa, Mussarela, Carne Seca'),
    ('Calabresa, Perpperoni, Carne Seca'),
    ('Catupiry, Tomate, Cheddar'),
    ('Catupiry, Tomate, Bacon'),
    ('Catupiry, Tomate, Lombo'),
    ('Catupiry, Tomate, Ovo'),
    ('Catupiry, Tomate, Presunto'),
    ('Catupiry, Tomate, Frango'),
    ('Catupiry, Tomate, Palmito'),
    ('Catupiry, Tomate, Azeitona'),
    ('Catupiry, Tomate, Milho'),
    ('Catupiry, Tomate, Carne Moida'),
    ('Catupiry, Tomate, Brócolis'),
    ('Catupiry, Tomate, Mussarela'),
    ('Catupiry, Tomate, Perpperoni'),
    ('Catupiry, Tomate, Carne Seca'),
    ('Catupiry, Cheddar, Bacon'),
    ('Catupiry, Cheddar, Lombo'),
    ('Catupiry, Cheddar, Ovo'),
    ('Catupiry, Cheddar, Presunto'),
    ('Catupiry, Cheddar, Frango'),
    ('Catupiry, Cheddar, Palmito'),
    ('Catupiry, Cheddar, Azeitona'),
    ('Catupiry, Cheddar, Milho'),
    ('Catupiry, Cheddar, Carne Moida'),
    ('Catupiry, Cheddar, Brócolis'),
    ('Catupiry, Cheddar, Mussarela'),
    ('Catupiry, Cheddar, Perpperoni'),
    ('Catupiry, Cheddar, Carne Seca'),
    ('Catupiry, Bacon, Lombo'),
    ('Catupiry, Bacon, Ovo'),
    ('Catupiry, Bacon, Presunto'),
    ('Catupiry, Bacon, Frango'),
    ('Catupiry, Bacon, Palmito'),
    ('Catupiry, Bacon, Azeitona'),
    ('Catupiry, Bacon, Milho'),
    ('Catupiry, Bacon, Carne Moida'),
    ('Catupiry, Bacon, Brócolis'),
    ('Catupiry, Bacon, Mussarela'),
    ('Catupiry, Bacon, Perpperoni'),
    ('Catupiry, Bacon, Carne Seca'),
    ('Catupiry, Lombo, Ovo'),
    ('Catupiry, Lombo, Presunto'),
    ('Catupiry, Lombo, Frango'),
    ('Catupiry, Lombo, Palmito'),
    ('Catupiry, Lombo, Azeitona'),
    ('Catupiry, Lombo, Milho'),
    ('Catupiry, Lombo, Carne Moida'),
    ('Catupiry, Lombo, Brócolis'),
    ('Catupiry, Lombo, Mussarela'),
    ('Catupiry, Lombo, Perpperoni'),
    ('Catupiry, Lombo, Carne Seca'),
    ('Catupiry, Ovo, Presunto'),
    ('Catupiry, Ovo, Frango'),
    ('Catupiry, Ovo, Palmito'),
    ('Catupiry, Ovo, Azeitona'),
    ('Catupiry, Ovo, Milho'),
    ('Catupiry, Ovo, Carne Moida'),
    ('Catupiry, Ovo, Brócolis'),
    ('Catupiry, Ovo, Mussarela'),
    ('Catupiry, Ovo, Perpperoni'),
    ('Catupiry, Ovo, Carne Seca'),
    ('Catupiry, Presunto, Frango'),
    ('Catupiry, Presunto, Palmito'),
    ('Catupiry, Presunto, Azeitona'),
    ('Catupiry, Presunto, Milho'),
    ('Catupiry, Presunto, Carne Moida'),
    ('Catupiry, Presunto, Brócolis'),
    ('Catupiry, Presunto, Mussarela'),
    ('Catupiry, Presunto, Perpperoni'),
    ('Catupiry, Presunto, Carne Seca'),
    ('Catupiry, Frango, Palmito'),
    ('Catupiry, Frango, Azeitona'),
    ('Catupiry, Frango, Milho'),
    ('Catupiry, Frango, Carne Moida'),
    ('Catupiry, Frango, Brócolis'),
    ('Catupiry, Frango, Mussarela'),
    ('Catupiry, Frango, Perpperoni'),
    ('Catupiry, Frango, Carne Seca'),
    ('Catupiry, Palmito, Azeitona'),
    ('Catupiry, Palmito, Milho'),
    ('Catupiry, Palmito, Carne Moida'),
    ('Catupiry, Palmito, Brócolis'),
    ('Catupiry, Palmito, Mussarela'),
    ('Catupiry, Palmito, Perpperoni'),
    ('Catupiry, Palmito, Carne Seca'),
    ('Catupiry, Azeitona, Milho'),
    ('Catupiry, Azeitona, Carne Moida'),
    ('Catupiry, Azeitona, Brócolis'),
    ('Catupiry, Azeitona, Mussarela'),
    ('Catupiry, Azeitona, Perpperoni'),
    ('Catupiry, Azeitona, Carne Seca'),
    ('Catupiry, Milho, Carne Moida'),
    ('Catupiry, Milho, Brócolis'),
    ('Catupiry, Milho, Mussarela'),
    ('Catupiry, Milho, Perpperoni'),
    ('Catupiry, Milho, Carne Seca'),
    ('Catupiry, Carne Moida, Brócolis'),
    ('Catupiry, Carne Moida, Mussarela'),
    ('Catupiry, Carne Moida, Perpperoni'),
    ('Catupiry, Carne Moida, Carne Seca'),
    ('Catupiry, Brócolis, Mussarela'),
    ('Catupiry, Brócolis, Perpperoni'),
    ('Catupiry, Brócolis, Carne Seca'),
    ('Catupiry, Mussarela, Perpperoni'),
    ('Catupiry, Mussarela, Carne Seca'),
    ('Catupiry, Perpperoni, Carne Seca'),
    ('Tomate, Cheddar, Bacon'),
    ('Tomate, Cheddar, Lombo'),
    ('Tomate, Cheddar, Ovo'),
    ('Tomate, Cheddar, Presunto'),
    ('Tomate, Cheddar, Frango'),
    ('Tomate, Cheddar, Palmito'),
    ('Tomate, Cheddar, Azeitona'),
    ('Tomate, Cheddar, Milho'),
    ('Tomate, Cheddar, Carne Moida'),
    ('Tomate, Cheddar, Brócolis'),
    ('Tomate, Cheddar, Mussarela'),
    ('Tomate, Cheddar, Perpperoni'),
    ('Tomate, Cheddar, Carne Seca'),
    ('Tomate, Bacon, Lombo'),
    ('Tomate, Bacon, Ovo'),
    ('Tomate, Bacon, Presunto'),
    ('Tomate, Bacon, Frango'),
    ('Tomate, Bacon, Palmito'),
    ('Tomate, Bacon, Azeitona'),
    ('Tomate, Bacon, Milho'),
    ('Tomate, Bacon, Carne Moida'),
    ('Tomate, Bacon, Brócolis'),
    ('Tomate, Bacon, Mussarela'),
    ('Tomate, Bacon, Perpperoni'),
    ('Tomate, Bacon, Carne Seca'),
    ('Tomate, Lombo, Ovo'),
    ('Tomate, Lombo, Presunto'),
    ('Tomate, Lombo, Frango'),
    ('Tomate, Lombo, Palmito'),
    ('Tomate, Lombo, Azeitona'),
    ('Tomate, Lombo, Milho'),
    ('Tomate, Lombo, Carne Moida'),
    ('Tomate, Lombo, Brócolis'),
    ('Tomate, Lombo, Mussarela'),
    ('Tomate, Lombo, Perpperoni'),
    ('Tomate, Lombo, Carne Seca'),
    ('Tomate, Ovo, Presunto'),
    ('Tomate, Ovo, Frango'),
    ('Tomate, Ovo, Palmito'),
    ('Tomate, Ovo, Azeitona'),
    ('Tomate, Ovo, Milho'),
    ('Tomate, Ovo, Carne Moida'),
    ('Tomate, Ovo, Brócolis'),
    ('Tomate, Ovo, Mussarela'),
    ('Tomate, Ovo, Perpperoni'),
    ('Tomate, Ovo, Carne Seca'),
    ('Tomate, Presunto, Frango'),
    ('Tomate, Presunto, Palmito'),
    ('Tomate, Presunto, Azeitona'),
    ('Tomate, Presunto, Milho'),
    ('Tomate, Presunto, Carne Moida'),
    ('Tomate, Presunto, Brócolis'),
    ('Tomate, Presunto, Mussarela'),
    ('Tomate, Presunto, Perpperoni'),
    ('Tomate, Presunto, Carne Seca'),
    ('Tomate, Frango, Palmito'),
    ('Tomate, Frango, Azeitona'),
    ('Tomate, Frango, Milho'),
    ('Tomate, Frango, Carne Moida'),
    ('Tomate, Frango, Brócolis'),
    ('Tomate, Frango, Mussarela'),
    ('Tomate, Frango, Perpperoni'),
    ('Tomate, Frango, Carne Seca'),
    ('Tomate, Palmito, Azeitona'),
    ('Tomate, Palmito, Milho'),
    ('Tomate, Palmito, Carne Moida'),
    ('Tomate, Palmito, Brócolis'),
    ('Tomate, Palmito, Mussarela'),
    ('Tomate, Palmito, Perpperoni'),
    ('Tomate, Palmito, Carne Seca'),
    ('Tomate, Azeitona, Milho'),
    ('Tomate, Azeitona, Carne Moida'),
    ('Tomate, Azeitona, Brócolis'),
    ('Tomate, Azeitona, Mussarela'),
    ('Tomate, Azeitona, Perpperoni'),
    ('Tomate, Azeitona, Carne Seca'),
    ('Tomate, Milho, Carne Moida'),
    ('Tomate, Milho, Brócolis'),
    ('Tomate, Milho, Mussarela'),
    ('Tomate, Milho, Perpperoni'),
    ('Tomate, Milho, Carne Seca'),
    ('Tomate, Carne Moida, Brócolis'),
    ('Tomate, Carne Moida, Mussarela'),
    ('Tomate, Carne Moida, Perpperoni'),
    ('Tomate, Carne Moida, Carne Seca'),
    ('Tomate, Brócolis, Mussarela'),
    ('Tomate, Brócolis, Perpperoni'),
    ('Tomate, Brócolis, Carne Seca'),
    ('Tomate, Mussarela, Perpperoni'),
    ('Tomate, Mussarela, Carne Seca'),
    ('Tomate, Perpperoni, Carne Seca'),
    ('Cheddar, Bacon, Lombo'),
    ('Cheddar, Bacon, Ovo'),
    ('Cheddar, Bacon, Presunto'),
    ('Cheddar, Bacon, Frango'),
    ('Cheddar, Bacon, Palmito'),
    ('Cheddar, Bacon, Azeitona'),
    ('Cheddar, Bacon, Milho'),
    ('Cheddar, Bacon, Carne Moida'),
    ('Cheddar, Bacon, Brócolis'),
    ('Cheddar, Bacon, Mussarela'),
    ('Cheddar, Bacon, Perpperoni'),
    ('Cheddar, Bacon, Carne Seca'),
    ('Cheddar, Lombo, Ovo'),
    ('Cheddar, Lombo, Presunto'),
    ('Cheddar, Lombo, Frango'),
    ('Cheddar, Lombo, Palmito'),
    ('Cheddar, Lombo, Azeitona'),
    ('Cheddar, Lombo, Milho'),
    ('Cheddar, Lombo, Carne Moida'),
    ('Cheddar, Lombo, Brócolis'),
    ('Cheddar, Lombo, Mussarela'),
    ('Cheddar, Lombo, Perpperoni'),
    ('Cheddar, Lombo, Carne Seca'),
    ('Cheddar, Ovo, Presunto'),
    ('Cheddar, Ovo, Frango'),
    ('Cheddar, Ovo, Palmito'),
    ('Cheddar, Ovo, Azeitona'),
    ('Cheddar, Ovo, Milho'),
    ('Cheddar, Ovo, Carne Moida'),
    ('Cheddar, Ovo, Brócolis'),
    ('Cheddar, Ovo, Mussarela'),
    ('Cheddar, Ovo, Perpperoni'),
    ('Cheddar, Ovo, Carne Seca'),
    ('Cheddar, Presunto, Frango'),
    ('Cheddar, Presunto, Palmito'),
    ('Cheddar, Presunto, Azeitona'),
    ('Cheddar, Presunto, Milho'),
    ('Cheddar, Presunto, Carne Moida'),
    ('Cheddar, Presunto, Brócolis'),
    ('Cheddar, Presunto, Mussarela'),
    ('Cheddar, Presunto, Perpperoni'),
    ('Cheddar, Presunto, Carne Seca'),
    ('Cheddar, Frango, Palmito'),
    ('Cheddar, Frango, Azeitona'),
    ('Cheddar, Frango, Milho'),
    ('Cheddar, Frango, Carne Moida'),
    ('Cheddar, Frango, Brócolis'),
    ('Cheddar, Frango, Mussarela'),
    ('Cheddar, Frango, Perpperoni'),
    ('Cheddar, Frango, Carne Seca'),
    ('Cheddar, Palmito, Azeitona'),
    ('Cheddar, Palmito, Milho'),
    ('Cheddar, Palmito, Carne Moida'),
    ('Cheddar, Palmito, Brócolis'),
    ('Cheddar, Palmito, Mussarela'),
    ('Cheddar, Palmito, Perpperoni'),
    ('Cheddar, Palmito, Carne Seca'),
    ('Cheddar, Azeitona, Milho'),
    ('Cheddar, Azeitona, Carne Moida'),
    ('Cheddar, Azeitona, Brócolis'),
    ('Cheddar, Azeitona, Mussarela'),
    ('Cheddar, Azeitona, Perpperoni'),
    ('Cheddar, Azeitona, Carne Seca'),
    ('Cheddar, Milho, Carne Moida'),
    ('Cheddar, Milho, Brócolis'),
    ('Cheddar, Milho, Mussarela'),
    ('Cheddar, Milho, Perpperoni'),
    ('Cheddar, Milho, Carne Seca'),
    ('Cheddar, Carne Moida, Brócolis'),
    ('Cheddar, Carne Moida, Mussarela'),
    ('Cheddar, Carne Moida, Perpperoni'),
    ('Cheddar, Carne Moida, Carne Seca'),
    ('Cheddar, Brócolis, Mussarela'),
    ('Cheddar, Brócolis, Perpperoni'),
    ('Cheddar, Brócolis, Carne Seca'),
    ('Cheddar, Mussarela, Perpperoni'),
    ('Cheddar, Mussarela, Carne Seca'),
    ('Cheddar, Perpperoni, Carne Seca'),
    ('Bacon, Lombo, Ovo'),
    ('Bacon, Lombo, Presunto'),
    ('Bacon, Lombo, Frango'),
    ('Bacon, Lombo, Palmito'),
    ('Bacon, Lombo, Azeitona'),
    ('Bacon, Lombo, Milho'),
    ('Bacon, Lombo, Carne Moida'),
    ('Bacon, Lombo, Brócolis'),
    ('Bacon, Lombo, Mussarela'),
    ('Bacon, Lombo, Perpperoni'),
    ('Bacon, Lombo, Carne Seca'),
    ('Bacon, Ovo, Presunto'),
    ('Bacon, Ovo, Frango'),
    ('Bacon, Ovo, Palmito'),
    ('Bacon, Ovo, Azeitona'),
    ('Bacon, Ovo, Milho'),
    ('Bacon, Ovo, Carne Moida'),
    ('Bacon, Ovo, Brócolis'),
    ('Bacon, Ovo, Mussarela'),
    ('Bacon, Ovo, Perpperoni'),
    ('Bacon, Ovo, Carne Seca'),
    ('Bacon, Presunto, Frango'),
    ('Bacon, Presunto, Palmito'),
    ('Bacon, Presunto, Azeitona'),
    ('Bacon, Presunto, Milho'),
    ('Bacon, Presunto, Carne Moida'),
    ('Bacon, Presunto, Brócolis'),
    ('Bacon, Presunto, Mussarela'),
    ('Bacon, Presunto, Perpperoni'),
    ('Bacon, Presunto, Carne Seca'),
    ('Bacon, Frango, Palmito'),
    ('Bacon, Frango, Azeitona'),
    ('Bacon, Frango, Milho'),
    ('Bacon, Frango, Carne Moida'),
    ('Bacon, Frango, Brócolis'),
    ('Bacon, Frango, Mussarela'),
    ('Bacon, Frango, Perpperoni'),
    ('Bacon, Frango, Carne Seca'),
    ('Bacon, Palmito, Azeitona'),
    ('Bacon, Palmito, Milho'),
    ('Bacon, Palmito, Carne Moida'),
    ('Bacon, Palmito, Brócolis'),
    ('Bacon, Palmito, Mussarela'),
    ('Bacon, Palmito, Perpperoni'),
    ('Bacon, Palmito, Carne Seca'),
    ('Bacon, Azeitona, Milho'),
    ('Bacon, Azeitona, Carne Moida'),
    ('Bacon, Azeitona, Brócolis'),
    ('Bacon, Azeitona, Mussarela'),
    ('Bacon, Azeitona, Perpperoni'),
    ('Bacon, Azeitona, Carne Seca'),
    ('Bacon, Milho, Carne Moida'),
    ('Bacon, Milho, Brócolis'),
    ('Bacon, Milho, Mussarela'),
    ('Bacon, Milho, Perpperoni'),
    ('Bacon, Milho, Carne Seca'),
    ('Bacon, Carne Moida, Brócolis'),
    ('Bacon, Carne Moida, Mussarela'),
    ('Bacon, Carne Moida, Perpperoni'),
    ('Bacon, Carne Moida, Carne Seca'),
    ('Bacon, Brócolis, Mussarela'),
    ('Bacon, Brócolis, Perpperoni'),
    ('Bacon, Brócolis, Carne Seca'),
    ('Bacon, Mussarela, Perpperoni'),
    ('Bacon, Mussarela, Carne Seca'),
    ('Bacon, Perpperoni, Carne Seca'),
    ('Lombo, Ovo, Presunto'),
    ('Lombo, Ovo, Frango'),
    ('Lombo, Ovo, Palmito'),
    ('Lombo, Ovo, Azeitona'),
    ('Lombo, Ovo, Milho'),
    ('Lombo, Ovo, Carne Moida'),
    ('Lombo, Ovo, Brócolis'),
    ('Lombo, Ovo, Mussarela'),
    ('Lombo, Ovo, Perpperoni'),
    ('Lombo, Ovo, Carne Seca'),
    ('Lombo, Presunto, Frango'),
    ('Lombo, Presunto, Palmito'),
    ('Lombo, Presunto, Azeitona'),
    ('Lombo, Presunto, Milho'),
    ('Lombo, Presunto, Carne Moida'),
    ('Lombo, Presunto, Brócolis'),
    ('Lombo, Presunto, Mussarela'),
    ('Lombo, Presunto, Perpperoni'),
    ('Lombo, Presunto, Carne Seca'),
    ('Lombo, Frango, Palmito'),
    ('Lombo, Frango, Azeitona'),
    ('Lombo, Frango, Milho'),
    ('Lombo, Frango, Carne Moida'),
    ('Lombo, Frango, Brócolis'),
    ('Lombo, Frango, Mussarela'),
    ('Lombo, Frango, Perpperoni'),
    ('Lombo, Frango, Carne Seca'),
    ('Lombo, Palmito, Azeitona'),
    ('Lombo, Palmito, Milho'),
    ('Lombo, Palmito, Carne Moida'),
    ('Lombo, Palmito, Brócolis'),
    ('Lombo, Palmito, Mussarela'),
    ('Lombo, Palmito, Perpperoni'),
    ('Lombo, Palmito, Carne Seca'),
    ('Lombo, Azeitona, Milho'),
    ('Lombo, Azeitona, Carne Moida'),
    ('Lombo, Azeitona, Brócolis'),
    ('Lombo, Azeitona, Mussarela'),
    ('Lombo, Azeitona, Perpperoni'),
    ('Lombo, Azeitona, Carne Seca'),
    ('Lombo, Milho, Carne Moida'),
    ('Lombo, Milho, Brócolis'),
    ('Lombo, Milho, Mussarela'),
    ('Lombo, Milho, Perpperoni'),
    ('Lombo, Milho, Carne Seca'),
    ('Lombo, Carne Moida, Brócolis'),
    ('Lombo, Carne Moida, Mussarela'),
    ('Lombo, Carne Moida, Perpperoni'),
    ('Lombo, Carne Moida, Carne Seca'),
    ('Lombo, Brócolis, Mussarela'),
    ('Lombo, Brócolis, Perpperoni'),
    ('Lombo, Brócolis, Carne Seca'),
    ('Lombo, Mussarela, Perpperoni'),
    ('Lombo, Mussarela, Carne Seca'),
    ('Lombo, Perpperoni, Carne Seca'),
    ('Ovo, Presunto, Frango'),
    ('Ovo, Presunto, Palmito'),
    ('Ovo, Presunto, Azeitona'),
    ('Ovo, Presunto, Milho'),
    ('Ovo, Presunto, Carne Moida'),
    ('Ovo, Presunto, Brócolis'),
    ('Ovo, Presunto, Mussarela'),
    ('Ovo, Presunto, Perpperoni'),
    ('Ovo, Presunto, Carne Seca'),
    ('Ovo, Frango, Palmito'),
    ('Ovo, Frango, Azeitona'),
    ('Ovo, Frango, Milho'),
    ('Ovo, Frango, Carne Moida'),
    ('Ovo, Frango, Brócolis'),
    ('Ovo, Frango, Mussarela'),
    ('Ovo, Frango, Perpperoni'),
    ('Ovo, Frango, Carne Seca'),
    ('Ovo, Palmito, Azeitona'),
    ('Ovo, Palmito, Milho'),
    ('Ovo, Palmito, Carne Moida'),
    ('Ovo, Palmito, Brócolis'),
    ('Ovo, Palmito, Mussarela'),
    ('Ovo, Palmito, Perpperoni'),
    ('Ovo, Palmito, Carne Seca'),
    ('Ovo, Azeitona, Milho'),
    ('Ovo, Azeitona, Carne Moida'),
    ('Ovo, Azeitona, Brócolis'),
    ('Ovo, Azeitona, Mussarela'),
    ('Ovo, Azeitona, Perpperoni'),
    ('Ovo, Azeitona, Carne Seca'),
    ('Ovo, Milho, Carne Moida'),
    ('Ovo, Milho, Brócolis'),
    ('Ovo, Milho, Mussarela'),
    ('Ovo, Milho, Perpperoni'),
    ('Ovo, Milho, Carne Seca'),
    ('Ovo, Carne Moida, Brócolis'),
    ('Ovo, Carne Moida, Mussarela'),
    ('Ovo, Carne Moida, Perpperoni'),
    ('Ovo, Carne Moida, Carne Seca'),
    ('Ovo, Brócolis, Mussarela'),
    ('Ovo, Brócolis, Perpperoni'),
    ('Ovo, Brócolis, Carne Seca'),
    ('Ovo, Mussarela, Perpperoni'),
    ('Ovo, Mussarela, Carne Seca'),
    ('Ovo, Perpperoni, Carne Seca'),
    ('Presunto, Frango, Palmito'),
    ('Presunto, Frango, Azeitona'),
    ('Presunto, Frango, Milho'),
    ('Presunto, Frango, Carne Moida'),
    ('Presunto, Frango, Brócolis'),
    ('Presunto, Frango, Mussarela'),
    ('Presunto, Frango, Perpperoni'),
    ('Presunto, Frango, Carne Seca'),
    ('Presunto, Palmito, Azeitona'),
    ('Presunto, Palmito, Milho'),
    ('Presunto, Palmito, Carne Moida'),
    ('Presunto, Palmito, Brócolis'),
    ('Presunto, Palmito, Mussarela'),
    ('Presunto, Palmito, Perpperoni'),
    ('Presunto, Palmito, Carne Seca'),
    ('Presunto, Azeitona, Milho'),
    ('Presunto, Azeitona, Carne Moida'),
    ('Presunto, Azeitona, Brócolis'),
    ('Presunto, Azeitona, Mussarela'),
    ('Presunto, Azeitona, Perpperoni'),
    ('Presunto, Azeitona, Carne Seca'),
    ('Presunto, Milho, Carne Moida'),
    ('Presunto, Milho, Brócolis'),
    ('Presunto, Milho, Mussarela'),
    ('Presunto, Milho, Perpperoni'),
    ('Presunto, Milho, Carne Seca'),
    ('Presunto, Carne Moida, Brócolis'),
    ('Presunto, Carne Moida, Mussarela'),
    ('Presunto, Carne Moida, Perpperoni'),
    ('Presunto, Carne Moida, Carne Seca'),
    ('Presunto, Brócolis, Mussarela'),
    ('Presunto, Brócolis, Perpperoni'),
    ('Presunto, Brócolis, Carne Seca'),
    ('Presunto, Mussarela, Perpperoni'),
    ('Presunto, Mussarela, Carne Seca'),
    ('Presunto, Perpperoni, Carne Seca'),
    ('Frango, Palmito, Azeitona'),
    ('Frango, Palmito, Milho'),
    ('Frango, Palmito, Carne Moida'),
    ('Frango, Palmito, Brócolis'),
    ('Frango, Palmito, Mussarela'),
    ('Frango, Palmito, Perpperoni'),
    ('Frango, Palmito, Carne Seca'),
    ('Frango, Azeitona, Milho'),
    ('Frango, Azeitona, Carne Moida'),
    ('Frango, Azeitona, Brócolis'),
    ('Frango, Azeitona, Mussarela'),
    ('Frango, Azeitona, Perpperoni'),
    ('Frango, Azeitona, Carne Seca'),
    ('Frango, Milho, Carne Moida'),
    ('Frango, Milho, Brócolis'),
    ('Frango, Milho, Mussarela'),
    ('Frango, Milho, Perpperoni'),
    ('Frango, Milho, Carne Seca'),
    ('Frango, Carne Moida, Brócolis'),
    ('Frango, Carne Moida, Mussarela'),
    ('Frango, Carne Moida, Perpperoni'),
    ('Frango, Carne Moida, Carne Seca'),
    ('Frango, Brócolis, Mussarela'),
    ('Frango, Brócolis, Perpperoni'),
    ('Frango, Brócolis, Carne Seca'),
    ('Frango, Mussarela, Perpperoni'),
    ('Frango, Mussarela, Carne Seca'),
    ('Frango, Perpperoni, Carne Seca'),
    ('Palmito, Azeitona, Milho'),
    ('Palmito, Azeitona, Carne Moida'),
    ('Palmito, Azeitona, Brócolis'),
    ('Palmito, Azeitona, Mussarela'),
    ('Palmito, Azeitona, Perpperoni'),
    ('Palmito, Azeitona, Carne Seca'),
    ('Palmito, Milho, Carne Moida'),
    ('Palmito, Milho, Brócolis'),
    ('Palmito, Milho, Mussarela'),
    ('Palmito, Milho, Perpperoni'),
    ('Palmito, Milho, Carne Seca'),
    ('Palmito, Carne Moida, Brócolis'),
    ('Palmito, Carne Moida, Mussarela'),
    ('Palmito, Carne Moida, Perpperoni'),
    ('Palmito, Carne Moida, Carne Seca'),
    ('Palmito, Brócolis, Mussarela'),
    ('Palmito, Brócolis, Perpperoni'),
    ('Palmito, Brócolis, Carne Seca'),
    ('Palmito, Mussarela, Perpperoni'),
    ('Palmito, Mussarela, Carne Seca'),
    ('Palmito, Perpperoni, Carne Seca'),
    ('Azeitona, Milho, Carne Moida'),
    ('Azeitona, Milho, Brócolis'),
    ('Azeitona, Milho, Mussarela'),
    ('Azeitona, Milho, Perpperoni'),
    ('Azeitona, Milho, Carne Seca'),
    ('Azeitona, Carne Moida, Brócolis'),
    ('Azeitona, Carne Moida, Mussarela'),
    ('Azeitona, Carne Moida, Perpperoni'),
    ('Azeitona, Carne Moida, Carne Seca'),
    ('Azeitona, Brócolis, Mussarela'),
    ('Azeitona, Brócolis, Perpperoni'),
    ('Azeitona, Brócolis, Carne Seca'),
    ('Azeitona, Mussarela, Perpperoni'),
    ('Azeitona, Mussarela, Carne Seca'),
    ('Azeitona, Perpperoni, Carne Seca'),
    ('Milho, Carne Moida, Brócolis'),
    ('Milho, Carne Moida, Mussarela'),
    ('Milho, Carne Moida, Perpperoni'),
    ('Milho, Carne Moida, Carne Seca'),
    ('Milho, Brócolis, Mussarela'),
    ('Milho, Brócolis, Perpperoni'),
    ('Milho, Brócolis, Carne Seca'),
    ('Milho, Mussarela, Perpperoni'),
    ('Milho, Mussarela, Carne Seca'),
    ('Milho, Perpperoni, Carne Seca'),
    ('Carne Moida, Brócolis, Mussarela'),
    ('Carne Moida, Brócolis, Perpperoni'),
    ('Carne Moida, Brócolis, Carne Seca'),
    ('Carne Moida, Mussarela, Perpperoni'),
    ('Carne Moida, Mussarela, Carne Seca'),
    ('Carne Moida, Perpperoni, Carne Seca'),
    ('Brócolis, Mussarela, Perpperoni'),
    ('Brócolis, Mussarela, Carne Seca'),
    ('Brócolis, Perpperoni, Carne Seca'),
    ('Mussarela, Perpperoni, Carne Seca')
;

UPDATE pasteis_salgados SET preco = 15.00;

UPDATE pasteis_salgados SET preco = 18.00 WHERE recheios LIKE '%Mussarela%';

UPDATE pasteis_salgados SET preco = 20.00 WHERE recheios LIKE '%Perpperoni%';

UPDATE pasteis_salgados SET preco = 20.00 WHERE recheios LIKE '%Carne Seca%';